services:
  db:
    image: postgres:16
    container_name: superset_db
    ports:
      - "5436:5432"
    volumes:
      - db_home:/var/lib/postgresql/data
    networks:
      - superset_network

  redis:
    image: redis:latest
    networks:
      - superset_network

  superset_link:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    depends_on:
      - db
      - redis
    networks:
      - superset_network

volumes:
  db_home:

networks:
  superset_network:
    driver: bridge
