services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: dwh
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5437:5432"

volumes:
  postgres_data: